### ISSUE TITLE
[Monk]Power Strike

### ISSUE THREAD

**Issue by Forcy** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#10]
**Current:** If you are at maximum Chi and keep spamming Jab - you will not lose the buff and you can spawn Chi Spheres forever and maintain the Power Strikes forever.

**Desired:** Power Strike is supposed to be consumed after one attack

**Comment by Maqlovin** [comment]
Additionally:

Current: Power strikes seems to recharge at odd times, I've seen a 36 seconds recharge time and a 24 seconds one.

Desired: Power Strikes should recharge every 20 seconds.
