### ISSUE TITLE
[Monk]Chi

### ISSUE THREAD

**Issue by Maqlovin** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#109]
Current: as soon as you generate chi out of combat, the chi nearly instantly dissapears.

Desired: Chi should remain for a while before slowly decaying, an exact source from back in 5.4 seems impossible to find, perhaps this Video will give you an idea, check out at 3:44, right after he casts uplift out of combat, 1 chi remains, keep watching untill the chi decays, it seems to be ~10 seconds. https://www.youtube.com/watch?v=iBzHe42lOWk

**Comment by Zerixx** [comment]
```
if (!IsInCombat())
    addvalue += -1.0f; // remove 1 each 10 sec
```

Willing to bet that will fix it.

**Comment by Maqlovin** [comment]
it appears to be fixed at this point yeah
