### ISSUE TITLE
[Monk]Summon Jade Serpent Statue

### ISSUE THREAD

**Issue by Maqlovin** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#113]
Current:
1) When the statue is summoned, you don't get a mini icon near your character frame, thus you can't remove the statue unless you summon a new one or wait the duration.
2) When casting Soothing mist, your statue will channel a replica of the soothing mist, but the channel will instantly stop after the first tick.
3) Eminence healing from Invoke Xuen, the white tiger doesn't trigger from the statue.

Desired:
1) When the statue is summoned, you get a mini icon near your character frame, which removes the statue by rightclicking the icon.
2) The statue should channel soothing mist for the entire duration of your soothing mist channeling, if the target chosen by the statue is at full health, it should automatically change it's target to an injured target.
3) Xuen's damage should be converted into eminence healing.

**Comment by Zerixx** [comment]
This seems to work as of 5.4.8.
