### ISSUE TITLE
Glyphs

### ISSUE THREAD

**Issue by Dzuvpacabra** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#123]
Glyphs disapear from "Learned glyph list", but they stay if you equip them. Unequiped and learned glyphs disapear after relog.

How it should work: once you learn a glyph, it should remain learned forever.

**Comment by Zerixx** [comment]
I haven't yet taken the time to update the glyph saving. Will get onto that soon. Thanks for the report.

-Z
