### ISSUE TITLE
Warrior

### ISSUE THREAD

**Issue by Tatzi** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#125]
- [x] Heroic Leap - Leaping through the air works, but doesnt deal damage to nearby targets(8yard range)
- [x] Shockwave - causing damage to 3 or more targets DOESNT lower cooldown to 20sec.
- [x] Thunder Clap - weakened blow effect has very short range(should be 8yards aoe).
- [x] Unable to switch to Battle Stance (no problems switching to or between Defence and Berserker stance).
- [x] Unable to equip tier items (they grey out in bag). Can attempt to equip several at once. Starter chestpiece I can both remove and reequip. 
- [x] Every 2-5 min I suddenly die and ressurect almost instantly.
  Edit: Only happened when GM modify health was set to absolute max (lowered my modified HP and I do not die now)
- [x] Bladestorm - do not hit anything but primary target (if I am attacking it). should hit every targets within 8 yards for 120% weapon dmg every 1 sec for 6 seconds. 
- [x] Gong-Lu, Strength of Xuen (ID 102249) the procc does 1 (2dmg if crit).

**Comment by Zerixx** [comment]
>  Gong-Lu, Strength of Xuen (ID 102249) the procc does 1 (2dmg if crit).

Won't fix until 5.4.8 is ready for release. By this, I mean when we open SoO.

**Comment by Zerixx** [comment]
Everything is fixed as of: https://github.com/ServerProject/Pandaria-Core/commit/46bd7918031f2f149558eb40f5f3faffc212d8d5
