### ISSUE TITLE
NPC

### ISSUE THREAD

**Issue by Tatzi** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#126]
- [ ] Some (not all) of the Docile Island Boars in the north / north-eastern part of Darkspear Isle are "dead" but walking around. They are not hostile, but you can attack them and they attack back. They are unkillable. 
- [ ] Unable to interact with Mei Francis (exotic Mounts) in Dalaran city.

**Comment by Zerixx** [comment]
Not seeing these issues anymore, so gonna close.
