### ISSUE TITLE
Questgiver

### ISSUE THREAD

**Issue by Tatzi** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#127]
- [ ] A fresh troll warrior are able to pick up the starter monk quests (not just the starter warr quests). This begins from the first quest npc you encounter. he send you to both warr and monk trainer and you are able to keep doing the quest chain for monks.
  First quest giver (that sends you to both monk and warr trainer) is: Jin'thala
  Monk trainer you are sent too: Zabrax
  Warrior trainer you are sent too: Nortet
- [ ] Charge does not work, there is simply no effect. You start with charge in stead of receiving it at lvl 3, though it comments if you are too far away or too close. Also, you are able to complete the quest "The Arts of a Warrior" (where you are supposed to charge a Tiki Target) just by beating it to death.

**Comment by Zerixx** [comment]
Fixed when quests fixes were applied.
