### ISSUE TITLE
General MoP

### ISSUE THREAD

**Issue by Tatzi** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#128]
- [x] Keep getting crash innside Shrone of Two Moons:
  This application as encountered a critical error: 
  ERROR #132 (0x85100084) Fatal exception!
  Program: F\MoP\WoW MoP.exe
  ProcessID: 62696
  Exception: 0xC0000005 (ACCESS_VIOLATION) at 0023:0051B6C7
  The instruction at 0x0051B6C7 referenced memory at 0x00000028
  The memory could not be read

Edit: I only get that crash if I GM fly in there (so far at least)
Reedit: I now crashed in Shrine of the Two Moons with speed set to 10 and flying off
- [x] Unable to interact with bankers and raid armor vendor innside Shrine of Two Moons. PS: When I attempt to interact with Raidvendors, "interact with armorer / blacksmither" sound but no inventory opens. 
  Tu'Aho Patchcutter, Ki'agnuu, Nadina Stargem, Blizzix Sparkshiv. (raid vendors)
  Vaultkeeper Goldpenny, Vaultkeeper kan, Vaultkeeper Shifen.
- [x] The riding trainer and flightmaster in Shrine of the Two Moons (golden terrace) have disappeared. name = Skydancer Shun.
  I have learned all skills, but there are an insane ammount of greyed out "Flight Master's Lisence" which I can't purchase for 250g. 
- [x] Unable to interact with Madam Vee Luo in Shrine of Two Moons (innkeeper) she replies, but no window open of any kind and no other sound is played.
- [x] I can interact with Brewmaster Skye (innkeeper in Shrine of Two Moon 2nd floor), but I can't "make this inn your home". When I press the option, the window disappear but my HS is still set to previous location. 
- [x] I attempted a couple of other locations, and I were not able to set a new inn as home.
- [x] the two vendors who are supposed to be sitting on the Grand Expedition Yak, Mystic Birdhat and Cousin Slowhands, are stuck underneath the mount. 
- [ ] the ground speed of Heavenly Crimson Cloud Serpent is the same as normal running speed for toons. Not 100% increase (flight speed works correctly) 
- [x] Silvermoont Delegation Guardian in Grommas Hold are walking around and disappearing / reappearing. They should be stationary.

**Comment by Zerixx** [comment]
Seems like a memory leak. I bet I botched a packet structure. Will check it out.

**Comment by Zerixx** [comment]
https://github.com/ServerProject/Pandaria-Core/commit/8623514b3f296b54be4c2ff8b56eb84d3634253f

Fixes:

> I can interact with Brewmaster Skye (innkeeper in Shrine of Two Moon 2nd floor), but I can't "make this inn your home". When I press the option, the window disappear but my HS is still set to previous location.
> 
> I attempted a couple of other locations, and I were not able to set a new inn as home.
