### ISSUE TITLE
Changing talents & Class Specialization

### ISSUE THREAD

**Issue by Maqlovin** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#129]
Currently it's impossible to change your talents (Class trainer & tome of the clear mind) or your class specialization (Class trainer).

Tested on multiple classes, so it's not class related I'd assume.

**Comment by Maqlovin** [comment]
Activating your primary specc again after buying dual talent doesn't seem to work, nothing happens when clicking "activate".

**Comment by Zerixx** [comment]
Currently in the works of being fixed :)

**Comment by Zerixx** [comment]
Fixed as of: https://github.com/ServerProject/Pandaria-Core/commit/1a5060cc44f13e034a827a8f7067c0088ae180d7
