### ISSUE TITLE
[Shaman]Spirit Link Totem

### ISSUE THREAD

**Issue by Forcy** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#13]
**Current:** Spirit Link Totem has a placeholder box model

**Desired:** Spirit Link Totem should have Air Totem model just like other Air Totems

**Comment by ghost** [comment]
Core issue since the template for the Spirit Link Totem, when added manually using GM commands displays the Spirit Link Totem correctly. Need to look at the spell script for this.

**Comment by ghost** [comment]
Fixed by: [b6e5c3c](https://github.com/ServerProject/pandaria-core/commit/aa207fe5c50bec98e6a9512bbdfe2da43b6e5c3c)
