### ISSUE TITLE
Mana issue

### ISSUE THREAD

**Issue by Dzuvpacabra** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#131]
Mana bugs visualy. When you have lets say 5% of mana, and you cast a spell, it will for a moment show that you have 100% mana, and after a moment or after you finish casting spell, it will be restored back to 5%. If you dont have enough mana for a certain spell, and the bugs shows that you have 100% mana, you still wont be able to cast it. (its visual bug only)

**Comment by Zerixx** [comment]
Fixed: https://github.com/ServerProject/Pandaria-Core/commit/7676a40b1ba8a03f845974aee2bcdf2b5f853d2d
