### ISSUE TITLE
Pet issues

### ISSUE THREAD

**Issue by Dzuvpacabra** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#132]
PET

GENERAL PET BUGS:
- [ ] Attack - doesnt work.
- [ ] Follow - doesnt work.
- [ ] Assist mode - doesnt work.
- [ ] Defensive mode - doesnt work.
- [ ] Passive mode - doesnt work.
- [ ] Dismiss pet - doesnt work.
- [ ] "Move to" option - doesnt work.
- [ ] Pet doesnt disapear after player dies.
- [ ] Most of the pet abilities cant be used.

**Comment by Zerixx** [comment]
It's on the list :)

-Z

**Comment by Zerixx** [comment]
Fixed

**Comment by Zerixx** [comment]
This was fixed a long time ago, not sure why it was never closed!
