### ISSUE TITLE
Gear visualy disapearing bug

### ISSUE THREAD

**Issue by Dzuvpacabra** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#135]
Lets say you have 5/5 gladiator's gear set equipped and full offparts, including trinkets etc etc(full gear). Now when you remove one trinkets, lets say first one, and you put it in bag, the head will visualy disapear and it wont display head info if you put mouse on "head" icon. It will display it like its empty slot. And if you remove second trinket, it will do the same to neck. Its all visual, stats and set bonus stays. Here are some screenshots:
1. http://i.imgur.com/BIckGrC.jpg - here you see me wearing full gear, 5/5 set
2. http://i.imgur.com/BYAnOMR.jpg - I removed trinkets, and head and neck disapeared(visualy only). And you can see it displaying i'm wearing 3/5 only(removed legs), and that im missing 4x set bonus, but you can see by my energy, the "missing head" is actually there.
3. http://i.imgur.com/zf5gFn9.jpg - me removing chest and legs, thus losing 4x bonus.

this happens on other classes too

**Comment by Zerixx** [comment]
This happens on all classes, all characters. I still don't know why. Perhaps an update field.

**Comment by Zerixx** [comment]
Fixed.
