### ISSUE TITLE
White hits critical strikes 

### ISSUE THREAD

**Issue by Dzuvpacabra** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#138]
In combat log, and visualy, they act as they were normal attacks:

http://i.imgur.com/tGopUCc.jpg - you can see clearly critical strike, but combat log logs it as normal attack, and visualy the numbers dont pop out as they should when critical strike hits, they pop like normal attacks. 

http://i.imgur.com/0QvUYpI.jpg 
http://i.imgur.com/KMdJsN3.jpg

Another examples

For special abilities, you can see clearly its critical strike both visualy and in combat log.

**Comment by Zerixx** [comment]
Fixed.
