### ISSUE TITLE
Quest [Riverpaw Gnoll Bounty]

### ISSUE THREAD

**Issue by Dzuvpacabra** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#139]
"Bring 8 Painted Gnoll Armbands(#782) to Deputy Rainer at the barracks."

Issue: When you collect 8 Painted gnoll armbands, you are still unable to complete the quest. In quest log it says [completed] and theres a yellow questionmark on minimap, but when you go to npc to complete quest, this happens and you are unable to complete quest http://i.imgur.com/6P2vqa1.jpg

**Comment by Zerixx** [comment]
https://github.com/ServerProject/Pandaria-Core/commit/c0422173bbb2c3c2c774797989b6cc29a62ed5f4

Fixed. Closing all issues.
