### ISSUE TITLE
Looting mobs

### ISSUE THREAD

**Issue by Dzuvpacabra** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#142]
- [x] When you kill a mob and if loot copper/silver/gold it will loot it but it will visualy stay like you havent looted it.
- [x] When you loot any item that isnt copper/silver/gold, loot window closes, making looting stuff annoying. Same happens with Chests.

**Comment by Nzzoth** [comment]
Fix denied reopened.

**Comment by ghost** [comment]
Fixed in https://github.com/ServerProject/Pandaria-Core/commit/53d34c5fb313aa3b9541a880b75a4613b6fc1893
