### ISSUE TITLE
Quest [Jasperlode Mine]

### ISSUE THREAD

**Issue by Dzuvpacabra** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#143]
"Explore the Jasperlode Mine, then report back to Marshal Dughan in Goldshire."

After exploring mine(yellow text says its completed) there is visual bug on minimap, saying you havent explored it, and questlog doesnt show that quest is "completed" as it should. But you can still complete it.

**Comment by Zerixx** [comment]
Yeah I gotta look into area triggers soon.
