### ISSUE TITLE
[Rogue] Glyph of Decoy (id: 42956)

### ISSUE THREAD

**Issue by Dzuvpacabra** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#149]
- [ ] Glyph of Decoy - When you Vanish, you leave behind a brief illusion that very closely resembles you. - Doesnt work. Should be non clickable, 100% visible (not stealth like) copy of you standing still for a second or two/three. After that, your copy will disappear in smoke. http://wow.zamimg.com/uploads/screenshots/resized/395428.jpg

^wowhead

**Comment by Zerixx** [comment]
Fixed: https://github.com/ServerProject/Pandaria-Core/commit/76e1e48d41aecb9337b014cb63e756c9163f69e3
