### ISSUE TITLE
[Core]Resource Bars

### ISSUE THREAD

**Issue by Forcy** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#15]
**Description:** Extra resource bars (Demonic Fury, Soul Shards, Holy Power etc) are sometimes not showing up for all classes. This issue appears to be 'random' and currently I am unable to find an exact way of reproducing it.

**Comment by Tudi** [comment]
Just saying that i can reproduce this bug even on blizzard live servers and WOD. It's been a few years since this bug started to happen. I tried to improve it on cataclysm, but it seems to be somewhat client related. Client sometimes skips updating self.

**Comment by Zerixx** [comment]
Won't fix.
