### ISSUE TITLE
[Rogue] Anticipation 

### ISSUE THREAD

**Issue by Dzuvpacabra** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#153]
How it should work: If you use mutilate on target that already has 5 combo points, you should get 2 anticipation charges(not 1), and if you crit that mutilate, you should get 3 anticipation charges.

Same happens when you have shadowblades on. Critical hits with mutilate + shadowblades are generating 4 combo points.(3 original combo points from mutilate crit + shadowblades)

How it works on feenix: There are examples when you have 5 combo points already on your target:
Mutilate(non crit) + shadowblades = 1 anticipation charge instead of 3.
Mutilate(OFFHAND CRIT ONLY) + shadowblades = 1 anticipation charges instead of 4.
Mutilate(MAINHAND CRIT ONLY) + shadowblades = 2 anticipation charges instead of 4.
Mutilate(non crit) = 1 anticipation charges instead of 2 anticipation charges.
Mutilate(crit, either mainhand or offhand) = 2 anticipation charges instead of 3 anticipation charges.

it shouldnt  matter if critical is from mainhand or offhand. Whatever weapon crits, you get +1 combo point from seal fate.

Combo points generate how they should outside of Anticipation.

**Comment by Zerixx** [comment]
This is no longer an issue.
