### ISSUE TITLE
[Priest] Shadow Orbs

### ISSUE THREAD

**Issue by Dzuvpacabra** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#155]
They work, but visualy they dont appear as they should. 

Example:

How it works on feenix: 
If you have 3 orbs, and you cast Devouring plague/SW:D, it consumes all 3 orbs, but visualy it consumes only 1 orb, and 2 orbs stay like they are not spent but you cant cast anything with those 2 orbs.

How it should work:
Spells like Devouring plague or Shadow word: Death, should visualy consume all orbs, no matter if its 1 or 3.

**Comment by Zerixx** [comment]
Fixed: https://github.com/ServerProject/Pandaria-Core/commit/7676a40b1ba8a03f845974aee2bcdf2b5f853d2d
