### ISSUE TITLE
Instant cast spell procs

### ISSUE THREAD

**Issue by Dzuvpacabra** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#157]
Spells procs that gives you instant cast of certain spells like Lava Surge(elemental) giving you instant Lava burst, or Divine Insight talent(priest) giving you instant mind blast cast, they cant be casted while moving and they should(cuz its instant cast spell).

**Comment by Zerixx** [comment]
Moving to a new master issue for this on our actual repo. Thank you for finding this.
