### ISSUE TITLE
[Priest] Shadowy Apparition

### ISSUE THREAD

**Issue by Dzuvpacabra** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#158]
Shadowy Apparition(78203) - When your Shadow Word: Pain damage over time critically strikes, you also create a shadowy version of yourself that floats towards the target and deals (45% of Spell power) Shadow damage.

Doesnt work.

**Comment by Zerixx** [comment]
Fixed: https://github.com/ServerProject/Pandaria-Core/commit/76e1e48d41aecb9337b014cb63e756c9163f69e3
