### ISSUE TITLE
[Priest] From darkness comes light - Surge of Darkness and Divine Insight

### ISSUE THREAD

**Issue by Dzuvpacabra** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#159]
- [ ] DIVINE INSIGHT:

How it works on feenix: when it procs gives mindblast an instant cast, but if you dont cast mind blast, and in meantime if second proc overrides first one, it will bug and you will have to cast mindblast.

How it should work: Each time this talent procs, you should be able to cast instant mind blast. No matter if there are multiple procs overriding eachother.
- [ ] FROM DARKNESS COMES LIGHT - SURGE OF DARKNESS:

Same bug mechanic as divine insight, if you get 2x stacks of Surge of darkness, and then you get proc that overrides those 2 stacks, it bugs just like Divine Insight, instead of Instant Mind Spike, you need to cast it.

**Comment by Zerixx** [comment]
Moving to a new master issue for this on our actual repo. Thank you for finding this.
