### ISSUE TITLE
[Core]Dungeon Finder stuck on loading screen 

### ISSUE THREAD

**Issue by Forcy** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#16]
**Description:** The game client gets "stuck" on full loading screen upon joining a dungeon by using the Dungeon Finder in game feature.

**Reproduction:** To reproduce this issue you will need 5 clients.
1. On each one of the clients create a Human Paladin2. Execute .levelup 15 command on every character3. Invite all 5 characters in a party group4. With the leader of the group open the Dungeon Finder (default key is "I") and queue for a random dungeon.

Note: You will have to select your class role upon joining the dungeon. One character has to be "Tank", second one "Healer" and the rest 3 "Damage"

http://oi60.tinypic.com/255rk7t.jpg

Observe that all 5 clients will be stuck on full loading screen after joining the dungeon

http://oi59.tinypic.com/xpcugn.jpg

If you close and re-open the client, the game proceeds normally. Also I do suspect that this issue might be present upon joining Arena and Battlegrounds games.

**Comment by Tudi** [comment]
please test https://github.com/Tudi/pandaria-core/commit/4096b251090f6d924f1c5fa609dea02235918721 
Should make sure there are no new issues

**Comment by ghost** [comment]
Resolved in 5.4.8
