### ISSUE TITLE
[Priest] Spectral Guise

### ISSUE THREAD

**Issue by Dzuvpacabra** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#162]
Spectral Guise talent(112833) - Your shadow blurs into the darkness, leaving your true form behind. As a shadow you are stealthed, but remain in combat. Lasts 6 sec or until your true form is hit by 3 direct attacks.

Bug: It doesnt spawn your true form

**Comment by Zerixx** [comment]
Fixed: https://github.com/ServerProject/Pandaria-Core/commit/76e1e48d41aecb9337b014cb63e756c9163f69e3
