### ISSUE TITLE
Instant spell procs overrides

### ISSUE THREAD

**Issue by Dzuvpacabra** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#163]
#159 - Every spell mechanic, that works like these talents/passive spells, have this kind of bug.

Brain Freeze(frost mage), Lava Surge(elemental), Maelstorm weapon(enha shaman) and probably many more have this kind of bug. Meaning if proc that gives you instant cast of certain spell, procs again without you using that proc to cast that spell, it will bug and you wont be able to cast it instantly anymore.

**Comment by Zerixx** [comment]
Moving to a new master issue for this on our actual repo. Thank you for finding this.
