### ISSUE TITLE
[Warlock] Agony, false formula

### ISSUE THREAD

**Issue by Dzuvpacabra** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#166]
Spell: Agony - id:980
original formula http://www.wowhead.com/spell=980/agony#changelog take it from 5.4.1

how it works on feenix: 
http://i.imgur.com/7HaiPRS.jpg
http://i.imgur.com/fNRPf7F.jpg
It increases ALOT more than it should

This was tested with 119 spell power, and with 24.80% mastery     

https://youtu.be/jeI10XjdUSo?t=105 you can see here, with 37k spell power he had 3-4k first thick and aound 17k max thick. On feenix you can currently with even less spell power do around 20k first thick and around 140k dmg with max stacks of agony

**Comment by Zerixx** [comment]
This actually appears to be working as intended. Guess it's just OP.
