### ISSUE TITLE
[Rogue]Killing Spree

### ISSUE THREAD

**Issue by Forcy** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#2]
**Current:** Killing Spree does nothing.

**Desired:** Its supposed to attack the target while porting on it/behind it every time it attacks - if Blade Flurry is toggled it should jump to the cleave target as well, provided there is one.

http://www.wowhead.com/spell=51690/killing-spree

> Step through the shadows to a visible enemy within 10 yards, attacking 7 times over 3 sec for 100% Physical damage with your main-hand and 100% Physical damage with your off-hand.
> 
> While Blade Flurry is active, each Killing Spree attack will teleport to and damage a different nearby enemy target.
> 
> The Rogue cannot be targeted or disabled while Killing Spree is active.

**Comment by ghost** [comment]
Fixed by commit: [e3d8a9](https://github.com/ServerProject/pandaria-db/commit/8761b9fe935768a8638ede5256b9945efde3d8a9)
