### ISSUE TITLE
[Priest]Halo

### ISSUE THREAD

**Issue by Forcy** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#20]
**Current:** Halo only has visual animation but does nothing

**Desired:** Creates a ring of Holy energy around you that quickly expands and grows in power, up to 30 yds away. Deals up to 46558 Holyu damage to enemies, and up to 77598 healing to allies, with the greatest effect at 25 yds.

**Comment by ghost** [comment]
Resolved
