### ISSUE TITLE
[Priest]Void Tendrils

### ISSUE THREAD

**Issue by Forcy** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#21]
**Current:** Void Tendrils does nothing.

**Desired:** Void Tendrils should summon Shadowy tendrils out of the ground, rooting up to 5 enemy targets with in 8 yards of the caster for 20 sec. Killing the tendril wil cancel the effect.

**Comment by ghost** [comment]
This seems to be showing the same symptoms as: https://github.com/FeenixServerProject/Pandaria_5.4.2_Issue_tracker/issues/9

It looks to be affecting some implicit targeting spells.

**Comment by ghost** [comment]
Resolved
