### ISSUE TITLE
[Quest] Death Comes From On High

### ISSUE THREAD

**Issue by Salce** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#22]
Issue 1

Current Situation : Completing Objective triggers "XXXX slain" message
Desired Situation : Completing Objective triggers "XXXX analyzed" message

issue 2 
Current Situation : Using Spell 5269 (Recall Eye of Acherus) doesnt remove Spell 51852 (The Eye of Acherus) from the player
Desired Situation : Using Spell 5269 (Recall Eye of Acherus) should remove Spell 51852 (The Eye of Acherus) from the player

**Comment by Zerixx** [comment]
Frankly, all of these quest issues just need to be held off until the new quest system is implemented.

**Comment by Nzzoth** [comment]
Tested on 5.4.2 closed.
