### ISSUE TITLE
[Object] Teleporter in Acherus

### ISSUE THREAD

**Issue by Salce** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#23]
Object 151235 is not working. It should teleport the player to this location : http://i.gyazo.com/d42fd214e3749550ef41b688c07b368c.png

Object 151237 is not working. It should teleport the player to this location : http://i.gyazo.com/255b8689102949c5304e2b71428cae27.png

**Comment by Nzzoth** [comment]
Tested on 5.4.2 closed.
