### ISSUE TITLE
[NPC] Noth The Plaguebringer

### ISSUE THREAD

**Issue by Salce** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#29]
NPC 28919 (Noth The Plaguebringer) offers the dialogue option "Noth, where is Heigan", he is currently missing the correct answers

These should be the possible answers : 

"Heigan is probably performing maintenance on his slime and crap filled dance studio.
"How dare you! Get out of my sight!"
"I can tell you where he's not..."
"NEVER say that name around me! Consider this your one and only warning!"
"That no good kiss-up is probably practising ballet in his chambers."

**Comment by ghost** [comment]
SMSG_NPC_TEXT_UPDATE packet needs work to handle either sending gossip entries and their probabilities of being said or picking gossip entries based on the probability tables and sending them.

It is likely other NPCs with multiple possible responses are also affected by this. Tested with the Mullen Gryphen Rider who has at least 3 or 4 responses yet only says 1 of those.

**Comment by Nzzoth** [comment]
Tested on 5.4.2 closed.
