### ISSUE TITLE
[Quest] How To Win Friends And Influence Enemies

### ISSUE THREAD

**Issue by Salce** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#30]
Hitting an enemy with Keleseth's Persuader equipped should have a chance to trigger quotes said by the player, but they seem to be empty. The following are possible quotes : 
You say: I'll tear the secrets from your soul! Tell me about the "Crimson Dawn" and your life may be spared!
You say: Tell me what you know about "Crimson Dawn" or the beatings will continue!
You say: I'm through being courteous with your kind, human! What is the "Crimson Dawn?"
You say: Is your life worth so little? Just tell me what I need to know about "Crimson Dawn" and I'll end your suffering quickly.
You say: I can keep this up for a very long time, Scarlet dog! Tell me about the "Crimson Dawn!"
You say: What is the "Crimson Dawn?"
You say: "Crimson Dawn!" What is it! Speak!

After breaking the enemy the quote said by player is again, empty. It should be : 
You say: LIES! The pain you are about to endure will be talked about for years to come!

**Comment by Nzzoth** [comment]
Tested on 5.4.2 closed.
