### ISSUE TITLE
[Quest] The Light of Dawn

### ISSUE THREAD

**Issue by Salce** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#33]
https://www.youtube.com/watch?v=cYUgIm5YjLc

^ All of this is missing. You can just accept and instantly complete.*

Here is the entire dialogue

Highlord Darion Mograine yells: Soldiers of the Scourge, stand ready! You will soon be able to unleash your fury upon the Argent Dawn!
Highlord Darion Mograine yells: The sky weeps at the devastation of sister earth! Soon, tears of blood will rain down upon us!
Highlord Darion Mograine yells: Death knights of Acherus, the death march begins!
Highlord Darion Mograine yells: Soldiers of the Scourge, death knights of Acherus, minions of the darkness: hear the call of the Highlord!
Highlord Darion Mograine yells: RISE!
<Thousands of Scourge rise up at the Highlord's command.>
Highlord Darion Mograine yells: The skies turn red with the blood of the fallen! The Lich King watches over us, minions! Onward! Leave only ashes and misery in your destructive wake!
<The army marches towards Light's Hope Chapel.>
Korfax, Champion of the Light yells: Scourge armies approach!
Lord Maxwell Tyrosus yells: Stand fast, brothers and sisters! The Light will prevail!
Highlord Darion Mograine says: Spare no one!
Highlord Darion Mograine yells: Rise, minions! Destroy them!
Highlord Darion Mograine says: Power...wanes...
Highlord Darion Mograine says: Ashbringer defies me...
Highlord Darion Mograine says: Minions, come to my aid!
Highlord Darion Mograine says: You will do as I command! I am in control here!
Highlord Darion Mograine says: What is this?! My... I cannot strike...
<After over a hundred Defenders of the Light fall, Highlord Tirion Fordring arrives.>
Highlord Tirion Fordring yells: You cannot win, Darion!
<Orbaz Bloodbane flees.>
Highlord Tirion Fordring yells: Bring them before the chapel!
<Highlord Darion Mograine kneels in defeat before Tirion Fordring.>
Highlord Darion Mograine says: Stand down, death knights. We have lost... The Light... This place... No hope...
Highlord Tirion Fordring says: Have you learned nothing, boy? You have become all that your father fought against! Like that coward, Arthas, you allowed yourself to be consumed by the darkness...the hate... Feeding upon the misery of those you tortured and killed!
Highlord Tirion Fordring says: Your master knows what lies beneath the chapel. It is why he dares not show his face! He's sent you and your death knights to meet their doom, Darion.
Highlord Tirion Fordring says: What you are feeling right now is the anguish of a thousand lost souls! Souls that you and your master brought here! The Light will tear you apart, Darion!
Highlord Darion Mograine says: Save your breath, old man. It might be the last you ever draw.
<Highlord Alexandros Mograine arrives.>
Highlord Alexandros Mograine says: My son! My dear, beautiful boy!
Highlord Darion Mograine says: Father!
Highlord Darion Mograine says: Argh...what...is...
<Highlord Darion Mograine becomes a shade of his past, and walks up to his father.>
Darion Mograine says: Father, you have returned!
<Darion Mograine hugs his father.>
Darion Mograine says: You have been gone a long time, father. I thought...
Highlord Alexandros Mograine says: Nothing could have kept me away from here, Darion. Not from my home and family.
Darion Mograine says: Father, I wish to join you in the war against the undead. I want to fight! I can sit idle no longer!
Highlord Alexandros Mograine says: Darion Mograine, you are barely of age to hold a sword, let alone battle the undead hordes of Lordaeron! I couldn't bear losing you. Even the thought...
Darion Mograine says: If I die, father, I would rather it be on my feet, standing in defiance against the undead legions! If I die, father, I die with you!
Highlord Alexandros Mograine says: My son, there will come a day when you will command the Ashbringer and, with it, mete justice across this land. I have no doubt that when that day finally comes, you will bring pride to our people and that Lordaeron will be a better place because of you. But, my son, that day is not today.
Highlord Alexandros Mograine says: Do not forget...
<Alexandros disappears, and the Lich King appears.>
The Lich King yells: Touching...
<Highlord Darion Mograine becomes himself again...and is now angry.>
Highlord Darion Mograine says: You have forsaken me, bastard! Face the might of Mograine!
The Lich King says: Pathetic...
The Lich King says: He's mine now...
Highlord Tirion Fordring says: You're a damned monster, Arthas!
The Lich King says: You were right, Fordring. I did send them in to die. Their lives are meaningless, but yours...
The Lich King says: How simple it was to draw the great Tirion Fordring out of hiding. You've left yourself exposed, paladin. Nothing will save you...
<The Lich King casts a spell on Tirion.>
<Highlord Tirion Fordring gasps for air.>
Lord Maxwell Tyrosus yells: ATTACK!!!
The Lich King yells: APOCALYPSE!
<The Lich King casts a powerful spell, killing the charging Defenders.>
Highlord Darion Mograine says: That day is not today...
Highlord Darion Mograine yells: Tirion!
<Darion throws the Corrupted Ashbringer to Tirion, who catches it. Tirion becomes awash with Light, and the Ashbringer is cleansed.>
<Highlord Darion Mograine collapses.>
Highlord Tirion Fordring yells: ARTHAS!!!!
The Lich King yells: What is this?
Highlord Tirion Fordring yells: Your end.
<Tirion charges towards the Lich King, Ashbringer in hand. The Lich King turns and begins to run.>
The Lich King yells: Impossible...
The Lich King yells: This... isn't... over...
The Lich King yells: When next we meet it won't be on holy ground, paladin.
<The Lich King disappears. Tirion walks over to where Darion lay.>
Highlord Tirion Fordring says: Rise, Darion, and listen...
Highlord Tirion Fordring says: We have all been witness to a terrible tragedy. The blood of good men has been shed upon this soil! Honorable knights, slain defending their lives - our lives!
Highlord Tirion Fordring says: And while such things can never be forgotten, we must remain vigilant in our cause!
Highlord Tirion Fordring says: The Lich King must answer for what he has done and must not be allowed to cause further destruction to our world.
Highlord Tirion Fordring says: I make a promise to you now, brothers and sisters: The Lich King will be defeated! On this day, I call for a union.
Highlord Tirion Fordring says: The Argent Dawn and the Order of the Silver Hand will come together as one! We will succeed where so many before us have failed!
Highlord Tirion Fordring says: We will take the fight to Arthas and tear down the walls of Icecrown!
Highlord Tirion Fordring yells: The Argent Crusade comes for you, Arthas!
Highlord Darion Mograine says: So too do the Knights of the Ebon Blade... While our kind has no place in your world, we will fight to bring an end to the Lich King. This I vow!
<Light washes over the chapel — the Light of Dawn is uncovered.>

**Comment by Nzzoth** [comment]
Tested on 5.4.2 closed.
