### ISSUE TITLE
[Warlock]Demonic Gateway

### ISSUE THREAD

**Issue by Forcy** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#4]
**Current:** The second Gateway simply dissapears and you cant click either of them

**Desired:** Create a demonic gateway between two locations. Stepping into the gateway causes any party member to be instantly transported to the other gateway.

Limit 5 charges. The portal generates one charge every 10 seconds and lasts 15 min.

**Comment by ghost** [comment]
Fixed by referenced commits. Charge depletion and regen needs to be tested. In Patch 6.0.2 the charge depletion and regen was removed and the spell distance decreased to 40 yards, but since this is MoP and not WoD, I assume that those changes are not required.
