### ISSUE TITLE
[Quest] Trolling for Information

### ISSUE THREAD

**Issue by Salce** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#43]
When approaching one of the 3 objective npcs, they should trigger a message 

Soothsayer Shi'kala (37108)
Da spirits be angry with us.
I don' know why the spirits be rejectin' us so.
Don' worry, child. Grik'nir gonna help us get through this.

Soothsayer Rikkari (37173)
What we gon' do now, you ask? We wait.
Grik'nir says he gon' talk to the elemental, get it to fight on our side.
Soon enough we take over dis valley. Soon enough.

Soothsayer Mirim'koa
Our land be a land of ice an' snow.
But beneath the earth, child, there always be fire.
De spirit come from deep down to talk with Grik'nir

After the message finishes you should complete the objective.

**Comment by Nzzoth** [comment]
Tested on 5.4.2 closed.
