### ISSUE TITLE
[Warlock]Archimonde's Darkness

### ISSUE THREAD

**Issue by Forcy** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#5]
**Current:** Archimonde's Darkness gives one charge with 20 seconds cooldown

**Desired:** Archimonde's Darkness should give 2 charges of Dark Soul with 2 minutes cooldown on each charge.

**Comment by ByteKiller** [comment]
Previously known as Archimonde's Vengeance and referred to as 'Archimonde's Vengeance' in core.

**Comment by Zerixx** [comment]
Fixed in 5.4.8.
