### ISSUE TITLE
[Quest] Finishin' The Job

### ISSUE THREAD

**Issue by Salce** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#60]
The detonator and the bombs are not spawned, making the quest incompletable.
Check the following video for reference

https://www.youtube.com/watch?v=dq1IwII-53c&feature=youtu.be

**Comment by devastator** [comment]
Should be scripted, the detonator and the bombs shouldn't be prespawned but spawn upon quest accept, perhaps visible only to the player that accepted the quest

**Comment by Nzzoth** [comment]
Tested on 5.4.2 closed.
