### ISSUE TITLE
[Core] Transmogrification

### ISSUE THREAD

**Issue by Forcy** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#68]
**Description:** The Transmogrification in game feature doesn't work at all. More information and details on how does the "transmog" feature works can be found here http://www.wowwiki.com/Transmogrification

**Comment by Forcy** [comment]
Fixed on PTR

**Comment by Zerixx** [comment]
This is fundamentally a packet IO issue, and once those packets are properly implemented, we can try to handle them.

**Comment by Nzzoth** [comment]
Tested on 5.4.2 closed.
