### ISSUE TITLE
[Quest] The Morons' League

### ISSUE THREAD

**Issue by Tester4** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#69]
Quest item 62650: "Dark Iron head"  does not drop from these NPCs:

ID 2743 50%
ID 2742 38%
ID 2740 23%
ID 2739 22%
http://www.wowhead.com/item=62650/dark-iron-head#dropped-by

**Comment by Nzzoth** [comment]
Tested on 5.4.2 closed.
