### ISSUE TITLE
[Hunter]A Murder of Crows

### ISSUE THREAD

**Issue by Forcy** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#7]
**Current:** A Murder of Crows doesn't deal any damage neither it has any animation on your target but it does consume Focus.

**Desired:** Summons a flock of crows to attack your target over the next 30 sec. If used on a target below 20% health, the cooldown is reduced to 60 seconds.

Note: I didn't find any information on how much damage/scaling A Murder of Crows should deal.

**Comment by ghost** [comment]
This will need implementing in the core, spell_hunter.cpp A Murder of Crows script. The crow summoning spell id 129179 is missing from the DBC which should spawn crows with creature id 61994. A custom movement generator may be needed to handle the crow flight paths towards the enemy.

The DBCs contain 4 other murder of crow spells which spawn the crows, but they will target you: 131637, 131951 and 131952. 131900 does damage to the target, no crows are visible until target is dead when they surround the corpse.
