### ISSUE TITLE
[Core] Potion Cooldowns and Combat States

### ISSUE THREAD

**Issue by Forcy** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#70]
**Current:** Potion cooldowns are only reset upon reloging or changeing zone (loading screen)

**Desired:** Potions should have 60 seconds cooldown out of combat.

http://www.wowwiki.com/Potion

> As of Patch 3.0.2, potions now have reduced cooldown of 1 minute. This cooldown does not begin until a player is outside of combat, meaning that if he/she takes a potion during a fight, the cooldown will not start until the fight is over. Some players will work around this mechanic by "pre-potting", using a potion such as Potion of Speed immediately before a boss is pulled and combat begins so that they will be able to use another potion during the fight.

**Comment by ghost** [comment]
Resolved
