### ISSUE TITLE
[Core] Loot Corpses disappear after 1 minute

### ISSUE THREAD

**Issue by Forcy** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#71]
**Current:** Once a creature is dead, its corpse disappears after 1 minute and players are unable to loot it. This applies to all kind of creatures, npcs (Didn't seems to be the case with bosses)

**Desired:** Corpses should remain present until they are supposed to respawn or one minute after being looted.

Note: It appears that this however works fine with 5 man bosses.

**Comment by Zerixx** [comment]
Fixed in 5.4.8.
