### ISSUE TITLE
[Quest] Recruitment

### ISSUE THREAD

**Issue by Salce** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#76]
Currently Scarlet Corpse is an attackable NPC that rewards quest progress when killed.
They should be right-clickable, make the player /point when used and then Darnell picking them up.
Check the video https://www.youtube.com/watch?v=GBmF9jGQnm4

**Comment by devastator** [comment]
Should be scripted

**Comment by Nzzoth** [comment]
Tested on 5.4.2 closed.

**Comment by Nzzoth** [comment]
Tested on 5.4.2 closed.
