### ISSUE TITLE
[Quests] Class Practice Quests in Deathknell.

### ISSUE THREAD

**Issue by Salce** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#77]
Magic Training (24965) - Mage
Of Light and Shadows (2496) - Priest
Stab! (24967) - Rogue
The Thrill of the Hunt (24964) - Hunter
Dark Deeds (24968) - Warlocks
Charging into Battle (24969) - Warrior
Tiger Palm (31147) - Monk

All of these quests are missing. They are part of the guiding quest chain so it's important we have them.

**Comment by devastator** [comment]
Quests exist in the db and have the related questgiver relations
