### ISSUE TITLE
[Hunter]Stampede

### ISSUE THREAD

**Issue by Forcy** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#8]
**Current:** Using Stampede does nothing

**Desired:** Summons all of your pets to fight your current target for 20 sec. Your pets deal 25% of their normal damage in Arenas and Battlegrounds while summoned this way.

**Comment by Tudi** [comment]
from athairne : 
summon (dire beast skill) with single display ID, estimated level 90 players pet damage (25% reduction)
From which we will make the stampende summons as exactly the same pet function from dire beast, except that we will use display ID of the current pet 5 times

It will function as an extra DPS spell, not a pet functionality. For BM specialisation hunters it should have some base increase in damage (without 25% damage reduction) to compensate

**Comment by Tudi** [comment]
started working on it
