### ISSUE TITLE
[Quest] Our Tribe, Imprisoned

### ISSUE THREAD

**Issue by Salce** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#81]
ID 24852

NPC 38345 should be standing still inside Object Quilboar Cage (IDS : 174988, 175020, 175019, 170533, 175032, 175034, 175035, 175036, 175031, ) and when interacting with the object they should say one of these following quotes and then despawn
"The quilboar will pay!"
"Thank the Earth Mother!"
"I can move again!"

**Comment by devastator** [comment]
Should be scripted

**Comment by Nzzoth** [comment]
Tested on 5.4.2 closed.
