### ISSUE TITLE
[Quest] Last Rites, First Rites

### ISSUE THREAD

**Issue by Salce** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#83]
ID 24861 is missing the RP part, as can be seen in the following video 

https://www.youtube.com/watch?v=p69K2uKNYLo&feature=youtu.be

This is the entire text

"Earth Mother, into your arms we give one of our own. She is Unaya Hawkwind, my mother, and Greatmother to us all; the wisest of our tribe.

May her spirit fly to you swiftly; may the winds carry her gently, and the grass whisper her name.

Watch over her as she has watched over us; let her look down on us with joy, through the eternal gaze of An'she and Mu'sha, until we join her in death.

For we are all born of you, and shall all return to you."

**Comment by Nzzoth** [comment]
Tested on 5.4.2 closed.
