### ISSUE TITLE
[Quest] Proving Pit

### ISSUE THREAD

**Issue by Salce** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#86]
24780, 24768, 24642, 26276, 24754, 24786, 24774, 24762

After talking to npc 39062 (Darkspear Jailor) he should say "Get in the pit and show us your stuff, boy!", then move to Darkspear Cage and open it, releasing the Captive Spitescale Scoute, which then should move into the pit and become targetable and hostile and say "The Sssea Witch will kill you all."

https://www.youtube.com/watch?v=umiTVvU06oU&feature=youtu.be

**Comment by Nzzoth** [comment]
Tested on 5.4.2 closed.
