### ISSUE TITLE
[Quest] Saving the Young

### ISSUE THREAD

**Issue by Salce** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#87]
Currently, killing NPC 39157 (Lost Bloodtalon Hatchling) rewards quest progress.
Instead, using Item 52283 (Bloodtalon Whistle) should cause all the Lost Bloodtalon Hatchlings close to the player to follow the player and reward quest progress.
Lost Bloodtalon Hatchlings should be friendly and non-attackable, instead of neutral and attackable.

**Comment by devastator** [comment]
Should be scripted

**Comment by Nzzoth** [comment]
Tested on 5.4.2 closed.
