### ISSUE TITLE
[Quest] Young and Vicious

### ISSUE THREAD

**Issue by Salce** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#88]
ID 24626
Should not be available before completing Quest 24625
When using item 50053 (Bloodtalon Lasso) on NPC 37989 (Swiftclaw) , the player should mount it and the message "Swiftclaw isn't stopping! Steer him back to the raptor pens near Darkspear Hold." should appear. The player should then ride into the Raptor Pens and the quest should complete.

https://www.youtube.com/watch?v=uPOsVTPGKC4&feature=youtu.be

**Comment by Nzzoth** [comment]
Tested on 5.4.2 closed.
