### ISSUE TITLE
[Monk]Chi Burst

### ISSUE THREAD

**Issue by Forcy** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#9]
**Current:** Chi Burst does nothing

**Desired:** You summon a torrent of Chi energy and hurl it forward, up to 40 yards, dealing 9371 Nature damage to all enemies, and 6637 healing to all allies in its path. Chi Bursts will always heal the Monk.

While casting Chi Burst, you continue to dodge, parry, and auto-attack.

**Comment by Maqlovin** [comment]
Desired: the damage and healing aren't static numbers, they go by the following formula: damage = 1325 + 1 \* att power *1.21  ;  healing = 1095 + 1 \* att power \* 1

Proof: http://i.imgur.com/pnl3fkX.png

**Comment by ghost** [comment]
chi burst HandleOnHit() method is never called despite being registered. It appears targets are never picked despite being in range.
