### ISSUE TITLE
[Quest] Breaking the Line

### ISSUE THREAD

**Issue by Salce** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#91]
When talking to NPC 38989 (Jornun) and chosing the option "Yes. Do you have a raptor that can take me there" the player should mount a Bloodtalon Trasher (ID: 38987)

**Comment by devastator** [comment]
Should be scripted, missing appropriate tables in db

**Comment by Nzzoth** [comment]
Tested on 5.4.2 closed.
