### ISSUE TITLE
[Quest] Only the worthy shall Pass

### ISSUE THREAD

**Issue by Salce** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#93]
When accepting the quest, the player should recieve the 3 following buffs 
102510 - Blessing of the Purple Flame
102509 - Blessing of the Blue Flame
102508 - Blessing of the Red Flame
Without these the quest is impossible to complete.

**Comment by Nzzoth** [comment]
Tested on 5.4.2 closed.
