### ISSUE TITLE
[Quest] The Horde Way

### ISSUE THREAD

**Issue by Salce** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#94]
Taken from WoWhead : 
"Garrosh will wonder around in the room and point out a few things to you. Then lecture you some - then lead you outside. Once you get outside - he jumps on his mount and heads off to the Valley of Honor leaving you behind to walk to the location. To get to the Valley of Honor, turn left out of the building, and when you step on the road, follow it west up the hill, then turn right and continue to follow the road until it forks, where you will see a big entryway to your right. Enter the enterway and it comes out in the Valley of Honor. Follow the trail along the lake, go over the bridge and up the hill and you will find Garrosh again standing in from of a building (the ring of honor)."
He currently doesn't do any of this, just has his dialogue.

**Comment by devastator** [comment]
Should be fixed in npc_garrosh_the_horde_way script

**Comment by Nzzoth** [comment]
Tested on 5.4.2 closed.
