### ISSUE TITLE
[Core] Movement animation

### ISSUE THREAD

**Issue by Salce** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#96]
Movement animation (walk/run) doesn't get updated properly, if your movement speed changes for whatever reason, the player is stuck in walking animation.

Example
.mod speed 5 
.cast 51372

**Comment by Forcy** [comment]
This also happens with other animations too, example do /dance move around and stop moving, observe that you will continue dancing

**Comment by Zerixx** [comment]
Not to resurrect an old issue, but this will be the case on all emulators within which the opcodes aren't handled.

This is a direct result of not having (specifically) ClientMoveUpdateRunSpeed, and PlayerCliMoveUpdateRunspeed/Ack. These thing need implemented into the core before you can expect this to work properly. Just stay tuned :)

**Comment by ghost** [comment]
Resolved
